const fs = require('fs');
const path = require('path');
const { getAllContentFiles } = require('./lib/utils');
const { parseAllContent } = require('./lib/content-parser');
const { ContentValidator } = require('./lib/validator');

const OUTPUT_PATH = path.join(__dirname, '../generated/encyclopedia-data.js');

// ── 1. Find files ───────────────────────────────────────────────────────────

const files = getAllContentFiles();

console.log('─'.repeat(50));
console.log('DATA GENERATION');
console.log('─'.repeat(50));

if (files.length === 0) {
  console.warn('⚠️  No markdown files found under content/encyclopedia.');
  console.warn('    Nothing to generate.');
  process.exit(0);
}

console.log(`📁 Files found:    ${files.length}`);

// ── 2. Parse ────────────────────────────────────────────────────────────────

const { entries, errors: parseErrors } = parseAllContent(files);
console.log(`📄 Entries parsed: ${entries.length}`);

if (parseErrors.length > 0) {
  console.error('\n❌ Parse errors — cannot generate:');
  parseErrors.forEach(e => console.error(`   ${e.file}\n   ${e.error}`));
  process.exit(1);
}

// ── 3. Validate ─────────────────────────────────────────────────────────────

const validator = new ContentValidator();
const results = validator.validateAll(entries);
console.log(validator.formatResults(results));

if (results.invalid > 0) {
  console.error('Validation failed. Fix errors before generating data.');
  process.exit(1);
}

// ── 4. Map to output shape (matches existing encyclopedia-data.js) ───────────

const outputEntries = entries.map(e => ({
  // Card-level metadata (encyclopedia index + connections)
  id: e.id,
  slug: e.id,
  name: e.name,
  url: e.url,
  quizDay: e.quizDay,
  vol: e.vol,
  dates: e.dates,
  category: e.category,
  barClass: e.barClass || '',
  tags: e.tags,
  desc: e.desc,

  // Quiz data
  question: e.question,
  options: e.options,
  answer: e.answer,
  answerText: e.answerText,
  subject: e.subject,

  // Narrative layers
  dailyStory: e.dailyStory,
  waitWhat: e.waitWhat,
  costImpact: e.costImpact,
  whyItMatters: e.whyItMatters,

  // Supporting content
  timeline: e.timeline,
  quote: e.quote,
}));

// ── 5. Build file content ────────────────────────────────────────────────────

const fileContent = `// generated/encyclopedia-data.js
// Auto-generated by scripts/generate-data.js — do not edit by hand.
// Source: content/encyclopedia/*.md
const ENCYCLOPEDIA = ${JSON.stringify(outputEntries, null, 2)};

// -----------------------------------------------------------------------
// getConnections(currentId, maxResults)
// Returns up to maxResults encyclopedia entries most related to currentId.
// Scoring: 1 point per shared tag. Ties broken by ENCYCLOPEDIA array order.
// -----------------------------------------------------------------------
function getConnections(currentId, maxResults) {
  maxResults = maxResults || 5;
  const current = ENCYCLOPEDIA.find(e => e.id === currentId);
  if (!current) return [];

  const seen = {};
  const unique = ENCYCLOPEDIA.filter(e => {
    if (seen[e.id]) return false;
    seen[e.id] = true;
    return true;
  });

  const scored = unique
    .filter(e => e.id !== currentId)
    .map(e => {
      const shared = e.tags.filter(t => current.tags.includes(t)).length;
      return { entry: e, score: shared };
    })
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score);

  return scored.slice(0, maxResults).map(s => s.entry);
}
`;

// ── 6. Write output ──────────────────────────────────────────────────────────

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, fileContent, 'utf-8');

console.log(`✅ Generated: generated/encyclopedia-data.js`);
console.log(`   Entries:   ${outputEntries.length}`);
